
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: multitenant
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./api
    environment:
      DATABASE_URL: postgres://admin:admin123@db:5432/multitenant
      JWT_SECRET: secretKey
      JWT_REFRESH_SECRET: refreshSecret
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./web
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata: